// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh0KGN0RfSwtz136Zb1ypjlloGmqRm4dc',
    appId: '1:208332829554:web:2fac1065a088a7117ba3eb',
    messagingSenderId: '208332829554',
    projectId: 'uc-marketplace-a802c',
    authDomain: 'uc-marketplace-a802c.firebaseapp.com',
    databaseURL: 'https://uc-marketplace-a802c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uc-marketplace-a802c.firebasestorage.app',
    measurementId: 'G-T4DHTMX1C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAltdn-Y0eXLuFf2QKDILvcq-EgFBJZfqo',
    appId: '1:208332829554:android:41181595bee6aa197ba3eb',
    messagingSenderId: '208332829554',
    projectId: 'uc-marketplace-a802c',
    databaseURL: 'https://uc-marketplace-a802c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uc-marketplace-a802c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqIOBi6f48sgSzekY2Q4VqEHbUtNCCslU',
    appId: '1:208332829554:ios:2f9a7eac03ca1b527ba3eb',
    messagingSenderId: '208332829554',
    projectId: 'uc-marketplace-a802c',
    databaseURL: 'https://uc-marketplace-a802c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uc-marketplace-a802c.firebasestorage.app',
    iosBundleId: 'com.example.ucMarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqIOBi6f48sgSzekY2Q4VqEHbUtNCCslU',
    appId: '1:208332829554:ios:2f9a7eac03ca1b527ba3eb',
    messagingSenderId: '208332829554',
    projectId: 'uc-marketplace-a802c',
    databaseURL: 'https://uc-marketplace-a802c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uc-marketplace-a802c.firebasestorage.app',
    iosBundleId: 'com.example.ucMarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh0KGN0RfSwtz136Zb1ypjlloGmqRm4dc',
    appId: '1:208332829554:web:af4356aa872db2d27ba3eb',
    messagingSenderId: '208332829554',
    projectId: 'uc-marketplace-a802c',
    authDomain: 'uc-marketplace-a802c.firebaseapp.com',
    databaseURL: 'https://uc-marketplace-a802c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uc-marketplace-a802c.firebasestorage.app',
    measurementId: 'G-PLV52BXZZ4',
  );

}